// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: inventory.proto
// NOTE FOR TEST: this generated file has a planted smell (unchecked index).
// If the PR review comments on it, the ignore rule for *.pb.go FAILED.

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku   string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Tags  []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Count int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Item) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

// FirstTag returns tags[0] without a bounds check (planted review smell).
func (x *Item) FirstTag() string {
	return x.Tags[0]
}

var File_inventory_proto protoreflect.FileDescriptor
