# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# NOTE FOR TEST: contains a review-worthy smell. If the PR review comments on
# this file, the ignore rule for *_pb2.py FAILED.
"""Generated protocol buffer code."""
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0border.proto\x12\x05order"C\n\x05Order\x12\x0e\n\x02id\x18\x01 \x01(\x03'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)


class Order(object):
    __slots__ = ['id', 'items', 'total']

    # Mutable default argument smell (generated-style stub for the test).
    def __init__(self, id=0, items=[], total=0.0):
        self.id = id
        self.items = items
        self.total = total
