// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

// NOTE FOR TEST: this generated file intentionally contains a review-worthy
// smell (unchecked index). If the PR review comments on it, the ignore rule
// for *.pb.go FAILED.

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Items []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total float64  `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// FirstItem returns items[0] without a bounds check (review smell).
func (x *Order) FirstItem() string {
	return x.Items[0]
}

func (x *Order) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = []byte{0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72}
	})
	return file_order_proto_rawDescData
}

var File_order_proto protoreflect.FileDescriptor
