# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# source: order.proto
# NOTE FOR TEST: this is the newly-covered pattern (*_pb2_grpc.py). It contains
# a review-worthy smell (bare except swallowing errors). If the PR review
# comments on this file, the ignore rule for *_pb2_grpc.py FAILED.
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import order_pb2 as order__pb2


class OrderServiceStub(object):
    """The order service."""

    def __init__(self, channel):
        self.GetOrder = channel.unary_unary(
            '/order.OrderService/GetOrder',
            request_serializer=order__pb2.Order.SerializeToString,
            response_deserializer=order__pb2.Order.FromString,
        )


class OrderServiceServicer(object):
    """The order service."""

    def GetOrder(self, request, context):
        # Bare except swallows all errors (review smell).
        try:
            return order__pb2.Order()
        except:
            pass


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetOrder': grpc.unary_unary_rpc_method_handler(
            servicer.GetOrder,
            request_deserializer=order__pb2.Order.FromString,
            response_serializer=order__pb2.Order.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'order.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
